### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by p3yot3** [Cryptcollector/ARG2.0#1]
I'm trying to compile using Berkley DB 4.8 as all my other merge mined coin wallets use this also, but am getting:

configure: error: libdb_cxx headers missing

I also tried using the  "--with-incompatible-bdb" option, but no joy. Is there a way to compile the daemon using the 4.8 DB?

Edit: Running Xubuntu 14.04 64bit

**Comment by Cryptcollector** [comment]
I'm afraid that we are using 5.1 and above, so, no sorry, my dev has said
that it would take changing the entire code to work with 4.8.

regards
Crypt

**Comment by p3yot3** [comment]
Oh dear.

It's not really a merge minable coin then, as all merge mined coins use BDB 4.8, bitcoin also. I'd suggest changing the BDB version to allow merge mining to work?

Regards.

**Comment by Cryptcollector** [comment]
hmm, sorry he gave me the wrong info, thought i was asking about another
coin.

It should be 4.8 compatable

I'll try to compile with 4.8 and get back to you.

**Comment by p3yot3** [comment]
That's what I thought, as other merge minable coins that use newer BDB's will also comple with the 4.8 version - but this wouldn't for some reason.....

Edit: I also couldn't run the QT, for the same reason. I would have to uninstall BDB 4.8 & install 5.1 in order to run it, but that would break all my other merge mined daemons. Not ideal.

**Comment by Cryptcollector** [comment]
Okay, you need to use 5.1 for the wallet db, this will not hamper the AUXPOW functionality of the daemon, as it only effects the wallet.dat portability.

You can install with libdb5.1 while not breaking the compatibility of of your existing libdb4.8 wallets.
Just follow the instructions within https://github.com/Cryptcollector/ARG2.0/blob/master/doc/build-unix.md there is a section in there on how to do this, Look at the Berkely DB section, there is a script there to do this.

Incidentally, DogeCoin has the same problem, it also is 5.1 dependant and gives the exact same error, just worded a little diferently.

**Comment by Cryptcollector** [comment]
i presume that this is now solved by my above post.

but to simplify the solution i created a post on the BCT ANN thread that will help by automating the process.
https://bitcointalk.org/index.php?topic=1432608.msg15382962#msg15382962

**Comment by p3yot3** [comment]
Yes, sorry - I should have closed this.
